/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;


import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author pc
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        
    
       
        // Centraliza a janela no meio do monitor
    this.setLocationRelativeTo(null);
    
 
    
    // Define qual botão será clicado quando o usuário apertar a tecla ENTER
    // (Substitua 'btnlogar' pelo nome da variável do seu botão de login)
    this.getRootPane().setDefaultButton(btnlogar);// configurar o botao de login da tela 
        
        
        setarLogoModerna(lblLogo, "/imagens/Logo.png", 200);
        
  // Carrega a imagem da pasta de recursos
    java.net.URL url = getClass().getResource("/imagens/Logo.png");
    
    if (url != null) {
        javax.swing.ImageIcon iconOriginal = new javax.swing.ImageIcon(url);
        
        // Define a largura desejada (ex: 180px) e calcula a altura mantendo a proporção
        int larguraDesejada = 500; 
        int alturaCalculada = (iconOriginal.getIconHeight() * larguraDesejada) / iconOriginal.getIconWidth();

        // Redimensiona com suavidade (SCALE_SMOOTH)
        java.awt.Image imagemRedimensionada = iconOriginal.getImage().getScaledInstance(
            larguraDesejada, 
            alturaCalculada, 
            java.awt.Image.SCALE_SMOOTH
        );

        // Aplica a imagem ajustada no JLabel
        lblLogo.setIcon(new javax.swing.ImageIcon(imagemRedimensionada));
        lblLogo.setText(""); // Remove qualquer texto padrão do label
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        btnlogar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.black);

        jLabel2.setText("Login:");

        jLabel1.setText("Senha:");

        btnlogar.setText("LOGAR!");
        btnlogar.addActionListener(this::btnlogarActionPerformed);

        txtsenha.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnlogar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(160, 302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnlogar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(384, 384, 384))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogarActionPerformed
        // TODO add your handling code here:
        
        //  Pegar os dados digitados pelo usuário
    String loginDigitado = txtlogin.getText().trim();
    String senhaDigitada = new String(txtsenha.getPassword()); 

    //  Validação simples de campos vazios
    if (loginDigitado.isEmpty() || senhaDigitada.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!");
        return;
    }

    try {
        //  Chamar a DAO para verificar no banco de dados
        dao.UsuarioDAO usuarioDAO = new dao.UsuarioDAO();
        model.Usuario usuarioLogado = usuarioDAO.autenticarUsuario(loginDigitado, senhaDigitada);

        //  Verificar se o usuário foi encontrado
        if (usuarioLogado != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bem-vindo(a), " + usuarioLogado.getLogin() + "!");
            
            // CONTROLE DE NÍVEL DE ACESSO:
            if (usuarioLogado.getPerfil() != null && usuarioLogado.getPerfil().equalsIgnoreCase("Administrador")) {
                // Se for Admin, abre a tela de Fornecedor
                telas.TelaFornecedor telaFornecedor = new telas.TelaFornecedor(); 
                telaFornecedor.setVisible(true);
            } else {
                // Se for usuário comum, abre a tela de vendas
                telas.RegistroV telaPrincipal = new telas.RegistroV(); 
                telaPrincipal.setVisible(true);
            }
            
            
            this.dispose(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro de Autenticação", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro técnico ao autenticar. Verifique o banco.", "Erro Interno", javax.swing.JOptionPane.ERROR_MESSAGE);
        System.out.println("Erro no login: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnlogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
        // Ativa o visual escuro moderno do FlatLaf
        com.formdev.flatlaf.FlatDarkLaf.setup();
    } catch (Exception ex) {
        System.err.println("Erro ao carregar o FlatLaf: " + ex.getMessage());
    }

    /* Cria e exibe a tela de Login */
    java.awt.EventQueue.invokeLater(() -> {
        new login().setVisible(true); // Substitua 'Login' pelo nome exato da sua classe
    });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables


    private void setarLogoModerna(JLabel label, String caminhoResource, int larguraDesejada) {
    try {
        URL url = getClass().getResource(caminhoResource);
        if (url == null) {
            System.err.println("Imagem não encontrada no caminho: " + caminhoResource);
            return;
        }
        
        ImageIcon iconOriginal = new ImageIcon(url);
        Image imgOriginal = iconOriginal.getImage();
        
        // Calcula a altura proporcionalmente para não distorcer a arte
        int larguraOriginal = iconOriginal.getIconWidth();
        int alturaOriginal = iconOriginal.getIconHeight();
        
        if (larguraOriginal <= 0 || alturaOriginal <= 0) return;
        
        int alturaDesejada = (larguraDesejada * alturaOriginal) / larguraOriginal;
        
        // Redimensiona com renderização de alta qualidade (SCALE_SMOOTH)
        Image imgRedimensionada = imgOriginal.getScaledInstance(
            larguraDesejada, 
            alturaDesejada, 
            Image.SCALE_SMOOTH
        );
        
        label.setIcon(new ImageIcon(imgRedimensionada));
        label.setText(""); // Limpa o texto da label caso exista
    } catch (Exception e) {
        System.err.println("Erro ao carregar a logo: " + e.getMessage());
        e.printStackTrace();
    }
    
    

    }}
