/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author pc
 */
public class Produto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Produto.class.getName());

    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
        
      this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Inicializa os dados da tela
        carregarFornecedoresNoCombo();
        preencherTabela();
    }

    // Método para buscar os fornecedores do banco e colocar no ComboBox
    private void carregarFornecedoresNoCombo() {
       try {
        dao.FornecedorDAO fDao = new dao.FornecedorDAO();
        java.util.List<model.Fornecedor> lista = fDao.listarTodos();
        
        jComboBox1.removeAllItems(); // Garante que a lista comece limpa
        
        
        jComboBox1.addItem("Selecione um fornecedor...");
        
        
        for (model.Fornecedor f : lista) {
            jComboBox1.addItem(f.getRazaoSocial());
        }
        
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Erro ao carregar fornecedores no combo", e);
    }
    }
   
   
    
    // Método para buscar os produtos do banco e desenhar na tabela (jTable1)
    private void preencherTabela() {
       try {
        dao.ProdutoDAO pDao = new dao.ProdutoDAO();
        java.util.List<model.Produto> lista = pDao.listarTodos();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0); // Limpa as linhas existentes para não duplicar
        
        // 1. Adicionamos a coluna "Fornecedor" no cabeçalho da tabela
        modelo.setColumnIdentifiers(new Object[]{"ID", "Nome", "Custo", "Venda", "Estoque", "Fornecedor"});
        
        for (model.Produto p : lista) {
            //  Razão Social do fornecedor associado de forma segura
            String nomeFornecedor = "";
            if (p.getFornecedor() != null) {
                nomeFornecedor = p.getFornecedor().getRazaoSocial();
            } else {
                nomeFornecedor = "Sem Fornecedor";
            }
            //  linha com a nova informação na tabela
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPrecoCusto(),
                p.getPrecoVenda(),
                p.getQuantidadeEstoque(),
                nomeFornecedor // <-- Nova coluna aqui!
            });
        }
     //  linha com a nova informação na tabela
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getPrecoCusto(),
                p.getPrecoVenda(),
                p.getQuantidadeEstoque(),
                nomeFornecedor // <-- Nova coluna aqui!
            });
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Erro ao preencher tabela de produtos", e);
    }
    }
        private void limparCampos() {
    txtnome.setText("");
    txtcusto.setText("");
    txtvenda.setText("");
    txtestoque.setText("");}
        
        
        
    
            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnexcluirp = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtcusto = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtvenda = new javax.swing.JTextField();
        txtestoque = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço de Custo:");

        jLabel3.setText("Quantidade no Estoque:");

        jLabel4.setText("Preço de Venda:");

        btnexcluirp.setText("Excluir:");
        btnexcluirp.addActionListener(this::btnexcluirpActionPerformed);

        btneditar.setText("Editar");
        btneditar.addActionListener(this::btneditarActionPerformed);

        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(this::btnsalvarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnexcluirp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(653, Short.MAX_VALUE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(177, 177, 177)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnexcluirp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if (txtnome.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "O nome do produto é obrigatório!");
            txtnome.requestFocus();
            return;
        }
        
        if (txtcusto.getText().trim().isEmpty() || txtvenda.getText().trim().isEmpty() || txtestoque.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos os campos numéricos devem ser preenchidos!");
            return;
        }
        
        if (jComboBox1.getSelectedIndex() <= 0) { // Valida seleção no ComboBox
            javax.swing.JOptionPane.showMessageDialog(this, "Você precisa selecionar um fornecedor válido!");
            return;
        }
        
        try {
            model.Produto produto = new model.Produto();
            produto.setNome(txtnome.getText().trim());
            produto.setPrecoCusto(Double.parseDouble(txtcusto.getText().trim()));
            produto.setPrecoVenda(Double.parseDouble(txtvenda.getText().trim()));
            produto.setQuantidadeEstoque(Integer.parseInt(txtestoque.getText().trim()));
            
            // Pega o fornecedor selecionado na ComboBox
            dao.FornecedorDAO fDao = new dao.FornecedorDAO();
            String razaoSelecionada = jComboBox1.getSelectedItem().toString();
            model.Fornecedor fornecedorAssociado = fDao.buscarPorRazao(razaoSelecionada);
            
            if (fornecedorAssociado != null) {
                produto.setFornecedor(fornecedorAssociado); 
            } else {
                throw new Exception("Fornecedor selecionado não foi encontrado no banco de dados.");
            }
            
            // Salva no banco
            dao.ProdutoDAO pDao = new dao.ProdutoDAO();
            pDao.salvar(produto);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            
            limparCampos();
            preencherTabela();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha custo, venda e estoque usando apenas números!");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar o produto: " + e.getMessage());
        }
    }
        
                                          

    private void btnexcluirpActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    int linhaSelecionada = jTable1.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para excluir!");
        return;
    }
    
    
    int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Tem certeza de que deseja excluir este produto?", 
        "Confirmar Exclusão", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );
   
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnexcluirpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirpActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = jTable1.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para excluir!");
            return;
        }
        
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza de que deseja excluir este produto?", 
            "Confirmar Exclusão", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int idProduto = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
                
                dao.ProdutoDAO pDao = new dao.ProdutoDAO();
                boolean sucesso = pDao.excluir(idProduto);
                
                if (sucesso) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                    preencherTabela();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível excluir o produto.");
                }
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao tentar excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnexcluirpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Produto().setVisible(true));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Produto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnexcluirp;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcusto;
    private javax.swing.JTextField txtestoque;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtvenda;
    // End of variables declaration//GEN-END:variables
}
